export const EDIT_VIRTUALIZATION = 'EDIT_VIRTUALIZATION';
export const UNDEPLOY_VIRTUALIZATION = 'EDIT_VIRTUALIZATION';
export const SET_VIRTUALIZATION = 'SET_VIRTUALIZATION';
export const AJAX_LOADING = 'AJAX_LOADING';